#version dcoker componse
version: "3.9"
#services are the constainers
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-users:
    container_name: msvc-users
    #id we want to build image from remote repository in Dockerhub, using de user name and reposiotrie name
    image: andresfeelip29/msvc-users
    #if we want to build an image to local from Dockerfile uses build:
    #build:
      #context: ./
      #dockerfile: ./msvc-users/Dockerfile
    #with the tag image is for using an existing image used image: or for set the tag of an image after build
    #image: msvc-users
    ports:
      - "8001:8001"
    env_file: ./msvc-users/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  msvc-courses:
    container_name: msvc-courses
    #id we want to build image from remote repository in Dockerhub, using de user name and reposiotrie name
    image: andresfeelip29/msvc-courses
    #if we want to build an image to local from Dockerfile uses build:
    #build:
      #context: ./
      #dockerfile: ./msvc-courses/Dockerfile
    #with the tag image is for using an existing image or for set the tag of an image after build
    #image: msvc-courses
    ports:
      - "8002:8002"
    env_file: ./msvc-courses/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-users
    restart: always

#define the volumes for persistence data
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

#define the network for de comunications the all services
networks:
  spring:
    name: spring




